package net.esper.view;

import net.esper.view.std.*;
import net.esper.view.ext.*;
import net.esper.view.window.LengthWindowView;
import net.esper.view.window.TimeWindowView;
import net.esper.view.window.ExternallyTimedWindowView;
import net.esper.view.window.TimeBatchView;
import net.esper.view.stat.*;

/**
 * Enum for all build-in views.
 */
public enum ViewEnum
{
    /**
     * Length window.
     */
    LENGTH_WINDOW("win", "length", LengthWindowView.class, true, null),

    /**
     * Time window.
     */
    TIME_WINDOW("win", "time", TimeWindowView.class, true, null),

    /**
     * Time batch.
     */
    TIME_BATCH("win","time_batch", TimeBatchView.class, true, null),

    /**
     * Externally timed window.
     */
    EXT_TIMED_WINDOW("win", "ext_timed", ExternallyTimedWindowView.class, true, null),

    /**
     * Size view.
     */
    SIZE("std", "size", SizeView.class, false, null),

    /**
     * Last event.
     */
    LAST_EVENT("std", "lastevent", LastElementView.class, false, null),

    /**
     * Unique.
     */
    UNIQUE_BY_PROPERTY("std", "unique", UniqueByPropertyView.class, true, null),

    /**
     * Group-by merge.
     */
    GROUP_MERGE("std", "merge", MergeView.class, true, null),

    /**
     * Group-by.
     */
    GROUP_PROPERTY("std", "groupby", GroupByView.class, true, GROUP_MERGE),

    /**
     * Univariate statistics.
     */
    UNIVARIATE_STATISTICS("stat", "uni", UnivariateStatisticsView.class, true, null),

    /**
     * Weighted avg.
     */
    WEIGHTED_AVERAGE("stat", "weighted_avg", WeightedAverageView.class, true, null),

    /**
     * Correlation.
     */
    CORRELATION("stat", "correl", CorrelationView.class, true, null),

    /**
     * Linest.
     */
    REGRESSION_LINEST("stat", "linest", RegressionLinestView.class, true, null),

    /**
     * Cubes.
     */
    MULTIDIM_VIEW("stat", "cube", MultiDimStatsView.class, true, null),

    /**
     * Sorted window.
     */
    SORT_WINDOW("ext", "sort", SortWindowView.class, true, null);


    private final String namespace;
    private final String name;
    private final Class clazz;
    private final boolean isRequiresParameters;
    private final ViewEnum mergeView;

    ViewEnum(String namespace, String name, Class clazz, boolean isRequiresParameters, ViewEnum mergeView)
    {
        this.namespace = namespace;
        this.name = name;
        this.clazz = clazz;
        this.isRequiresParameters = isRequiresParameters;
        this.mergeView = mergeView;
    }

    /**
     * Returns namespace that the object belongs to.
     * @return namespace
     */
    public String getNamespace()
    {
        return namespace;
    }

    /**
     * Returns name of the view that can be used to reference the view in a view expression.
     * @return short name of view
     */
    public String getName()
    {
        return name;
    }

    /**
     * Gets the implementation class underlying the view.
     * @return view implementation class
     */
    public Class getClazz()
    {
        return clazz;
    }

    /**
     * Returns true if the view requires one or more parameters, false if the view doesn't require any parameters.
     * @return true if at least one parameter is mandatory, false if there are no mandatory parameters
     */
    public boolean isRequiresParameters()
    {
        return isRequiresParameters;
    }

    /**
     * Returns the enumeration value of the view for merging the data generated by another view.
     * @return view enum for the merge view
     */
    public ViewEnum getMergeView()
    {
        return mergeView;
    }

    /**
     * Returns the view enumeration value given the name of the view.
     * @param namespace is the namespace name of the view
     * @param name is the short name of the view as used in view expressions
     * @return view enumeration value, or null if no such view name is among the enumerated values
     */
    public static ViewEnum forName(String namespace, String name)
    {
        for (ViewEnum viewEnum : ViewEnum.values())
        {
            if ((viewEnum.getNamespace().equals(namespace)) && (viewEnum.getName().equals(name)))
            {
                return viewEnum;
            }
        }

        return null;
    }
}
